stages:
  - triggers

trigger_dev:
  stage: triggers
  trigger:
    include: /gitlabconf/dev/.gitlab-ci.yml
  rules:
    # Triggered only when push, commit or merge request event come
    - if: $CI_COMMIT_BRANCH == "dev" || $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "dev"
      when: manual

# trigger_preprod:
#   stage: triggers
#   trigger:
#     include: /gitlabconf/preprod/.gitlab-ci.yml
#   rules:
#     # Manually triggered only when join request event come
#     - if: $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "preprod"
#       when: manual

# trigger_prod:
#   stage: triggers
#   trigger:
#     include: /gitlabconf/prod/.gitlab-ci.yml
#   rules:
#     # Manually triggered only when join request event come
#     - if: $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "preprod"
#       when: manual
