
stages: 
  - build
  - deploy
# Cache node_modules - speeds up future builds
cache:
  paths:
    - node_modules
variables:
  APP_ENV: "dev"
#--------------------------------#
react_build:
  stage: build
  # Build aşaması
  image: node:alpine
  script:
    - npm install
    - npm run build-${APP_ENV}
    - tar -cvzf build.tar.gz build/
  # Nereye kopyalanacağı ve ne build çıktısının ne kadar süre saklanacağını belirttiğimiz bölüm
  artifacts:
    expire_in: 1 day
    paths:
      - build.tar.gz
#--------------------------------#
react_deploy:
  stage: deploy
  needs: [react_build]
  image: alpine
    
  script:
      - apk add --no-cache rsync openssh
      - mkdir -p ~/.ssh
      - echo "$DEPLOY_HOST_SSH_PRIVATE_KEY" >> ~/.ssh/id_dsa
      - chmod 600 ~/.ssh/id_dsa
      - ssh-keyscan -t ecdsa 192.168.230.134 >> ~/.ssh/known_hosts
      - chmod 644 ~/.ssh/known_hosts
      - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'

      - scp build.tar.gz react-demo-user@192.168.230.134:/home/react-demo-user/react-project

      - ssh react-demo-user@192.168.230.134 "
           cd react-project/;
           pwd;
           ./update.sh
           "
